CREATE TABLE #AGREGACAO
(
	NF INT,
	Produto VARCHAR(100),
	Cliente VARCHAR(100),
	Quantidade INT,
	Valor NUMERIC(18,2),
	Dia INT
)

INSERT INTO #AGREGACAO VALUES
	(1, 'P001', 'C1', 8, 160, 5),
	(1, 'P002', 'C1', 2, 34, 5),
	(1, 'P003', 'C1', 1, 58, 5),
	(2, 'P002', 'C3', 20, 340, 7),
	(3, 'P001', 'C2', 12, 240, 8),
	(3, 'P002', 'C2', 5, 85, 8),
	(4, 'P001', 'C1', 2, 40, 10),
	(5, 'P003', 'C3', 4, 232, 15)

SELECT SUM(Valor) FROM #AGREGACAO

SELECT * FROM #AGREGACAO

SELECT SUM(Valor) FROM #AGREGACAO WHERE Cliente = 'C1'

SELECT COUNT(*) FROM #AGREGACAO

SELECT COUNT(*) FROM #AGREGACAO WHERE Cliente = 'C2'

SELECT AVG(Valor) FROM #AGREGACAO

SELECT AVG(Valor) FROM #AGREGACAO WHERE Cliente = 'C1'

SELECT MIN(Valor), MAX(Valor) FROM #AGREGACAO

SELECT MIN(Valor), MAX(Valor) FROM #AGREGACAO WHERE Cliente='C1'

SELECT Cliente, SUM(Valor) FROM #AGREGACAO GROUP BY Cliente

SELECT NF, COUNT(*) FROM #AGREGACAO GROUP BY NF

SELECT NF, AVG(Valor) FROM #AGREGACAO GROUP BY NF

SELECT NF, MIN(Valor), MAX(Valor) FROM #AGREGACAO GROUP BY NF

SELECT Cliente, SUM(Valor), COUNT(*) FROM #AGREGACAO GROUP BY Cliente

SELECT Cliente, SUM(Valor), COUNT(*) as Qtd FROM #AGREGACAO GROUP BY Cliente HAVING (SUM(Valor) >300)

SELECT Cliente, SUM(Valor), COUNT(*) as Qtd FROM #AGREGACAO GROUP BY Cliente HAVING (COUNT(*) > 2)